MARGIN = 0.15
ROAD_WIDTH = 20
CAR_RADIUS = 0.25 * ROAD_WIDTH

WIDTH = 600
HEIGHT = 600

VERTICAL_BLOCKS = 6
HORIZONTAL_BLOCKS = 6

MIN_TRAVEL_LENGTH = 2
MAX_TRAVEL_LENGTH = 5

MIN_CRUISE_SPEED = 14
MAX_CRUISE_SPEED = 30

MIN_ACCEL_SPEED = 8
MAX_ACCEL_SPEED = 15

ERROR = 0.001 * max(WIDTH, HEIGHT)

DISTANCE_ACCEPTANCE = 40
DISTANCE_FOR_RESPONSE = 40
